### ISSUE TITLE
Error: No suitable driver found for jdbc:sqlite

### ISSUE THREAD

**Issue by iwan-uschka** [bshannon/savenotes#7]
Just tried to run

```
java -ea -jar ~/Desktop/NOTES/apps/savenotes-master/target/savenotes.jar -f ~/Desktop/NOTES/data/NotesV7.storedata -d ~/output
```

without success:

```
No suitable driver found for jdbc:sqlite:/Users/iwanuschka/Desktop/NOTES/data/NotesV7.storedata
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.sql.Connection.createStatement()" because "conn" is null
	at SaveNotes.save(SaveNotes.java:177)
	at SaveNotes.main(SaveNotes.java:152)
```

`NotesV7.storedata` has been taken from a system running Mac OS Catalina.

Any idea?

**Comment by iwan-uschka** [comment]
On my part, there is no pressure here. I found another way to recover the data: https://github.com/ydkhatri/mac_apt/issues/46#issuecomment-766418508.
